"""Initial commit

Revision ID: d4a273582ce8
Revises: 
Create Date: 2016-07-30 07:18:05.131646

"""

# revision identifiers, used by Alembic.
revision = 'd4a273582ce8'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('idx')
    )
    op.create_table('kakaotalk',
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('unique_key', sa.String(length=32), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('strlength', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.idx'], ),
    sa.PrimaryKeyConstraint('idx'),
    sa.UniqueConstraint('unique_key')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kakaotalk')
    op.drop_table('user')
    ### end Alembic commands ###
